Budgeter/Controllers/HomeController.cs
using Budgeter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Budgeter.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            return View(db.HouseHolds.ToList().Where(p => p.IsDeleted == false));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Budgeter/Controllers/HouseHoldsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Budgeter.Models;
using Microsoft.AspNet.Identity;
using Budgeter.Models.Helpers;

namespace Budgeter.Controllers
{
    public class HouseHoldsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: HouseHolds
        public ActionResult Index()
        {
            return View(db.HouseHolds.ToList());
        }

        // GET: HouseHolds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }

        // GET: HouseHolds/Create
        public ActionResult Create(int? id)
        {
            var household = new HouseHold();

            string userId = User.Identity.GetUserId();
            household.CreatorId = userId;

            ViewBag.Id = id;
            ViewBag.CreatorId = new SelectList(db.Users, "Id", "FirstName");
            return View();
        }

        // POST: HouseHolds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,IsDeleted,CreatorId")] HouseHold household)
        {
            if (ModelState.IsValid)
            {
                household.CreatorId = User.Identity.GetUserId();
                db.HouseHolds.Add(household);
                // -------Added to work on budgets
                Budget budget = new Budget
                {
                    HouseHoldId = household.Id,
                    Household = db.HouseHolds.Find(household.Id),
                    Name = household.Name + "Budget",
                    Amount = 0

                };
                db.Budgets.Add(budget);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }
            //------- Added to work on budgets
            // ViewBag.CreatorId = new SelectList(db.Users, "Id", "FirstName", household.CreatorId);
            return View(household);
        }
        // GET: HouseHolds/Leave household/5
        public ActionResult leavehousehold(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }

        //POST: HouseHolds/Leave household/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult leavehousehold(int id)
        {
            HouseAssignHelper helper = new HouseAssignHelper(db);
            string userId = User.Identity.GetUserId();
            //helper.RemoveHouseFromUser(household.Id, user);

            helper.RemoveHouseFromUser(id, userId);
            db.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        // POST: HouseHolds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HouseHold houseHold = db.HouseHolds.Find(id);
            db.HouseHolds.Remove(houseHold);
            db.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: HouseHolds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }

        // POST: HouseHolds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,IsDeleted")] HouseHold houseHold)
        {
            if (ModelState.IsValid)
            {
                db.Entry(houseHold).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(houseHold);
        }

        // GET: HouseHolds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseHold houseHold = db.HouseHolds.Find(id);
            if (houseHold == null)
            {
                return HttpNotFound();
            }
            return View(houseHold);
        }
        //GET: Assign User to Houses
        //[Authorize(Roles = "Admin, HouseholdAdmin")]
        public ActionResult HouseAssign(int id)
        {
            var household = db.HouseHolds.Find(id);
            HouseAssignHelper helper = new HouseAssignHelper(db);
            var model = new HouseAssignUserViewModel();

            model.HouseHold = household;

            model.SelectedUsers = helper.ListAssignedUsers(id).Select(u => u.Id).ToArray();
            model.Users = new MultiSelectList(db.Users.Where(u => (u.FirstName != "N/A" && u.FirstName != "(Remove Assigned User)")).OrderBy(u => u.FirstName), "Id", "FirstName", model.SelectedUsers);


            return View(model);
        }

        //POST: Assign Users to House
        [HttpPost]
        //[Authorize(Roles = "HouseholdAdmin, Admin")]
        public ActionResult HouseAssign(HouseAssignUserViewModel model)
        {
            var household = db.HouseHolds.Find(model.HouseHold.Id);
            HouseAssignHelper helper = new HouseAssignHelper(db);

            foreach (var user in db.Users.Select(r => r.Id).ToList())
            {
                helper.RemoveHouseFromUser(household.Id, user);
            }
            if (model.SelectedUsers != null)
            {
                foreach (var user in model.SelectedUsers)
                {
                    helper.AddHouseToUser(household.Id, user);
                }
            }
            return RedirectToAction("Index", "Home");

        }

        //// POST: HouseHolds/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirm(int id)
        //{
        //    HouseHold houseHold = db.HouseHolds.Find(id);
        //    db.HouseHolds.Remove(houseHold);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

Budgeter/Controllers/InvitesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Budgeter.Models;
using Microsoft.AspNet.Identity;
using System.Net.Mail;
using System.Configuration;
using System.Threading.Tasks;

namespace Budgeter.Controllers
{
    public class InvitesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Invites
        public ActionResult Index()
        {
            return View(db.Invites.ToList());
        }

        // GET: Invites/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invite invite = db.Invites.Find(id);
            if (invite == null)
            {
                return HttpNotFound();
            }
            return View(invite);
        }

        // GET: Invites/Create
        public ActionResult Create(int? id)
        {
            ViewBag.HouseHoldId = id;
            return View();
        }

        // POST: Invites/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Email,HouseHoldId,Secret")] Invite invite, int hId)
        {
            if (ModelState.IsValid)
            {
                invite.HouseHoldId = hId;
            invite.Secret = Utilities.GenerateSecretCode();
                var email = new MailMessage(ConfigurationManager.AppSettings["username"], invite.Email)
            {
                Subject = "you are invited to join a new household",
                Body = "You have been invited to join a household inside Neena's Budget Planner. Select -Join- on log in, and input the code: " + invite.Secret + ".\n" + "Or, <a href=\"" + Url.Action( "InviteRegister", "Account" ,new {houseId = invite.HouseHoldId, secret = invite.Secret },Request.Url.Scheme) + "\">Click here</a> to join."
            };


            db.Invites.Add(invite);
            db.SaveChanges();

                var svc = new PersonalEmail();
                await svc.SendAsync(email);

                return RedirectToAction("Index");
        }

            return  View(invite);
    }

        // GET: Invites/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invite invite = db.Invites.Find(id);
            if (invite == null)
            {
                return HttpNotFound();
            }
            return View(invite);
        }

        // POST: Invites/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Email,HouseHoldId,Secret")] Invite invite)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invite).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(invite);
        }

        // GET: Invites/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invite invite = db.Invites.Find(id);
            if (invite == null)
            {
                return HttpNotFound();
            }
            return View(invite);
        }

        // POST: Invites/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invite invite = db.Invites.Find(id);
            db.Invites.Remove(invite);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Budgeter/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Budgeter.Models;

namespace Budgeter.Controllers
{
    public class ItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        public ActionResult Index()
        {
            var items = db.Items.Include(i => i.Budget).Include(i => i.Category);
            return View(items.ToList());
        }

        // GET: Items/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // GET: Items/Create
        public ActionResult Create(int? id)
        {
            ViewBag.BudgetId =id;
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryId,BudgetId,Amount,IsDeleted")] Item item, int BId)
        {
            if (ModelState.IsValid)
            {
                //....Added for budget
                item.BudgetId = BId;
                var budget = db.Budgets.Find(BId);
                if (budget != null)
                {
                    item.Budget = budget;
                    budget.Amount += item.Amount;
                }
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BudgetId = new SelectList(db.Budgets, "Id", "Name", item.BudgetId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", item.CategoryId);
            return View(item);
        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            ViewBag.BudgetId = new SelectList(db.Budgets, "Id", "Name", item.BudgetId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", item.CategoryId);
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryId,BudgetId,Amount,IsDeleted")] Item item)
        {
            if (ModelState.IsValid)
            {

                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BudgetId = new SelectList(db.Budgets, "Id", "Name", item.BudgetId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", item.CategoryId);
            return View(item);
        }

        // GET: Items/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Item item = db.Items.Find(id);
            db.Items.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Budgeter/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Budgeter/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Budgeter/Views/Home/Index.cshtml
@model IEnumerable<Budgeter.Models.HouseHold>
@using Microsoft.AspNet.Identity



@{
    ViewBag.Title = "Home Page";
    var userId = User.Identity.GetUserId();

}

@*@if (Request.IsAuthenticated)*@
{


    <h3 class="text-left">My house</h3>
    <p>
        <a href="@Url.Action("Create", "HouseHolds")" class="btn btn-success">Create New </a>
        <a href="@Url.Action("Index", "Items")" class="btn btn-warning">budgets details </a>


        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-3">
                        <div class="card-header" style="background-color:#91d57f">
                            <i class="fa fa-table"></i>
                            HOUSEHOLDS

                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered" width="100%" id="dataTable" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>Name</th>

                                            <th>Assigned Users</th>
                                            <th>Actions</th>

                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Name)
                                                </td>
                                                @*<td>
                                                        @Html.DisplayFor(modelItem => item.Body)
                                                    </td>*@
                                                <td>
                                                    @foreach (var user in item.Users)
                                                    {
                                                        @user.FirstName
                                                        <br />
                                                    }


                                                </td>
                                                <td>
                                                    @*<a href="@Url.Action("Create", "Items")" class="btn btn-success">Budget </a>*@

                                                    @*<a href="@Url.Action("Create", "Items", new { id = item.Id })" title="Budget" style="width: 26px ; height: 26px" class="btn btn-xs btn-success"><i class="fa  fa-bank"></i></a>*@

                                                    <a href="@Url.Action("Create", "Invites", new { id = item.Id })" title="Invite Users" style="width: 26px ; height: 16px" class="btn btn-xs btn-info"><i class="fa  fa-envelope"></i></a>
                                                    <a href="@Url.Action("HouseAssign", "HouseHolds", new { id = item.Id })" title="Assign" style="width: 26px ; height: 16px" class="btn btn-xs btn-info"><i class="fa  fa-user"></i></a>
                                                    <a href="@Url.Action("Edit", "HouseHolds", new { id = item.Id })" title="Edit" style="width: 26px ; height: 16px" class="btn btn-xs btn-warning"><i class="fa fa-edit"></i></a>
                                                    <a href="@Url.Action("Details", "HouseHolds", new { id = item.Id })" title="Details" style="width: 26px ; height: 16px" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>
                                                    <a href="@Url.Action("Delete", "HouseHolds", new { id = item.Id })" title="Delete" style="width: 26px ; height: 16px" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i></a>
                                                    @foreach (var budgets in item.Budgets)
                                                    {
                                                        <a href="@Url.Action("Create", "Items", new { id = budgets.Id })" title="Create Budget" style="width: 26px ; height: 16px" class="btn btn-xs btn-info"><i class="fa fa-bank"></i></a>
                                                    }
                                                    @foreach (var user in item.Users)
                                                    {
                                                        if (userId == user.Id)
                                                        {
                                                            @*@Html.ActionLink("Leave", "LeaveHouseHold", new { id = item.Id })*@
                                                            <a href="@Url.Action("LeaveHouseHold", "HouseHolds", new { id = item.Id })" title="Leave" style="width: 26px ; height: 16px" class="btn btn-xs btn-danger"><i class="fa fa-circle"></i></a>

                                                        }
                                                    }
                                                    <a href="@Url.Action("Create", "BankAccounts", new { id = item.Id })" title="Create New Account" style="width: 26px;height: 16px" class="btn btn-xs btn-success"><i class="fa fa-money"></i> </a>

                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer small text-muted">
                        </div>
                    </div>


                    @*</div>*@
                </div>
                @*<h4>Assigned Projects</h4>*@

                @*</div>*@
            </div>
        </div>

        <br />
        <br />
        <br />
        <br />
        <br />

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card mb-3">
                        <div class="card-header"style="background-color:#91d57f">
                            <i class="fa fa-table"></i>
                            Bank Account Details

                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-bordered dataTable2" width="100%" id="dataTable" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>HouseHold</th>

                                            <th>Bank</th>
                                            <th>Balance</th>
                                            <th>Actions</th>
                                            <th>Status</th>



                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {

                                            foreach (var account in item.BankAccount)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => account.household.Name)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => account.Name)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => account.Balance)
                                                        @*@account.Balance.ToString("C")*@
                                                    </td>
                                                    <td>
                                                        @*<a href="/Transactions/Create/1" title="Add Transactions" style="width: 26px ; height: 26px" class="btn btn-xs btn-success"><i class="fa fa-dollar"></i></a>*@
                                                        <a href="@Url.Action("Create", "Transactions", new { id = account.Id })" title="Add Transaction" style="width: 26px ; height: 16px" class="btn btn-xs btn-success"><i class="fa  fa-dollar"></i></a>
                                                        <a href="@Url.Action("Edit", "BankAccounts", new { id = account.Id })" title="Edit" style="width: 26px ; height: 16px" class="btn btn-xs btn-warning"><i class="fa  fa-edit"></i></a>
                                                        <a href="@Url.Action("Details", "BankAccounts", new { id = account.Id })" title="Details" style="width: 26px ; height: 16px" class="btn btn-xs btn-info"><i class="fa  fa-eye"></i></a>
                                                        <a href="@Url.Action("Delete", "BankAccounts", new { id = account.Id })" title="Delete" style="width: 26px ; height: 16px" class="btn btn-xs btn-danger"><i class="fa  fa-trash"></i></a>


                                                        @*<a href="/BankAccounts/Edit/1" title="Edit" style="width: 26px ; height: 26px" class="btn btn-xs btn-warning"><i class="fa fa-edit"></i></a>
                                                            <a href="/BankAccounts/Details/1" title="Details" style="width: 26px ; height: 26px" class="btn btn-xs btn-info"><i class="fa fa-eye"></i></a>
                                                            <a href="/BankAccounts/Delete/1" title="Delete" style="width: 26px ; height: 26px" class="btn btn-xs btn-danger"><i class="fa fa-trash-o"></i></a>*@
                                                    </td>
                                                    <td>

                                                        @if (account.Balance <= 0)
                                                        {
                                                            <em style="color:red">Account OverDrawn</em>
                                                        }
                                                        else
                                                        {
                                                            <em style="color:green"> Enough Money</em>
                                                        }




                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="card-footer small text-muted">
                        </div>
                    </div>


                    @*</div>*@
                </div>
                @*<h4>Assigned Projects</h4>*@

                @*</div>*@
            </div>
        </div>



        }
        <script>
            $(document).ready(function () {
                $(".dataTable1").dataTable();
            });
            $(document).ready(function () {
                $('.dataTable2').dataTable();
            });
            $(document).ready(function () {
                $(".dataTable3").dataTable();
            });
            $(document).ready(function () {
                $('.dataTable4').dataTable();
            });
        </script>